//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 05:58:35 PM EET 
//


package Sort.Emulation.Models.FromXSD;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Sort.Emulation.Models.FromXSD package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MSGBODYPAB_QNAME = new QName("", "PAB");
    private final static QName _MSGBODYSRB_QNAME = new QName("", "SRB");
    private final static QName _MSGBODYHPIC_QNAME = new QName("", "HPIC");
    private final static QName _MSGBODYPIB_QNAME = new QName("", "PIB");
    private final static QName _MSGBODYDSTAT_QNAME = new QName("", "DSTAT");
    private final static QName _MSGBODYDID_QNAME = new QName("", "DID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Sort.Emulation.Models.FromXSD
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MSG }
     * 
     */
    public MSG createMSG() {
        return new MSG();
    }

    /**
     * Create an instance of {@link MSG.BODY }
     * 
     */
    public MSG.BODY createMSGBODY() {
        return new MSG.BODY();
    }

    /**
     * Create an instance of {@link MSG.HEADER }
     * 
     */
    public MSG.HEADER createMSGHEADER() {
        return new MSG.HEADER();
    }

    /**
     * Create an instance of {@link MSG.BODY.PIB }
     * 
     */
    public MSG.BODY.PIB createMSGBODYPIB() {
        return new MSG.BODY.PIB();
    }

    /**
     * Create an instance of {@link MSG.BODY.PAB }
     * 
     */
    public MSG.BODY.PAB createMSGBODYPAB() {
        return new MSG.BODY.PAB();
    }

    /**
     * Create an instance of {@link MSG.BODY.SRB }
     * 
     */
    public MSG.BODY.SRB createMSGBODYSRB() {
        return new MSG.BODY.SRB();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSG.BODY.PAB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PAB", scope = MSG.BODY.class)
    public JAXBElement<MSG.BODY.PAB> createMSGBODYPAB(MSG.BODY.PAB value) {
        return new JAXBElement<MSG.BODY.PAB>(_MSGBODYPAB_QNAME, MSG.BODY.PAB.class, MSG.BODY.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSG.BODY.SRB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SRB", scope = MSG.BODY.class)
    public JAXBElement<MSG.BODY.SRB> createMSGBODYSRB(MSG.BODY.SRB value) {
        return new JAXBElement<MSG.BODY.SRB>(_MSGBODYSRB_QNAME, MSG.BODY.SRB.class, MSG.BODY.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HPIC", scope = MSG.BODY.class)
    public JAXBElement<String> createMSGBODYHPIC(String value) {
        return new JAXBElement<String>(_MSGBODYHPIC_QNAME, String.class, MSG.BODY.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSG.BODY.PIB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PIB", scope = MSG.BODY.class)
    public JAXBElement<MSG.BODY.PIB> createMSGBODYPIB(MSG.BODY.PIB value) {
        return new JAXBElement<MSG.BODY.PIB>(_MSGBODYPIB_QNAME, MSG.BODY.PIB.class, MSG.BODY.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DSTAT", scope = MSG.BODY.class)
    public JAXBElement<String> createMSGBODYDSTAT(String value) {
        return new JAXBElement<String>(_MSGBODYDSTAT_QNAME, String.class, MSG.BODY.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DID", scope = MSG.BODY.class)
    public JAXBElement<String> createMSGBODYDID(String value) {
        return new JAXBElement<String>(_MSGBODYDID_QNAME, String.class, MSG.BODY.class, value);
    }

}
